In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    ----------------


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Arryays in NumPy
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3])

# 2D array
arr2 = np.array([[1, 2], [3, 4]])

# Array of zeros
zeros = np.zeros((2, 3))

# Array of ones
ones = np.ones((3, 4))

# Array with a range of numbers
range_arr = np.arange(0, 10, 2)

# Linearly spaced array
linspace_arr = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1


In [3]:
arr1

array([1, 2, 3])

In [5]:
arr2


array([[1, 2],
       [3, 4]])

In [6]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
range_arr

array([0, 2, 4, 6, 8])

In [9]:
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
# Arry Operation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
sum_arr = arr1 + arr2

# Subtraction
diff_arr = arr1 - arr2

# Multiplication
prod_arr = arr1 * arr2

# Division
div_arr = arr1 / arr2


In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [14]:
sum_arr = arr1 + arr2
sum_arr

array([5, 7, 9])

In [15]:
diff_arr = arr1 - arr2
diff_arr 


array([-3, -3, -3])

In [16]:
prod_arr = arr1 * arr2
prod_arr

array([ 4, 10, 18])

In [17]:
div_arr = arr1 / arr2
div_arr

array([0.25, 0.4 , 0.5 ])

In [ ]:
# Broadcasting
arr = np.array([1, 2, 3])
scalar = 2
result = arr + scalar  # Adds 2 to each element of arr

# Broadcasting with two arrays of different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
result_broadcast = arr1 + arr2  # Will broadcast arr2 to match arr1's shape



In [20]:
arr = np.array([1, 2, 3])
scalar = 2
result = arr + scalar 


In [21]:
scalar

2

In [22]:
result

array([3, 4, 5])

In [23]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])
result_broadcast = arr1 + arr2  

In [24]:
result_broadcast

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [25]:
# Element wise operation
arr = np.array([1, 4, 9])

# Square root of each element
sqrt_arr = np.sqrt(arr)

# Sine of each element
sin_arr = np.sin(arr)


In [27]:
arr


array([1, 4, 9])

In [28]:
sqrt_arr

array([1., 2., 3.])

In [29]:
sin_arr

array([ 0.84147098, -0.7568025 ,  0.41211849])

In [31]:
# changing the shape
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3), 2 rows and 3 columns
print(arr.ndim)   # 2, number of dimensions


(2, 3)
2


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2x3
reshaped_arr = arr.reshape(2, 3)

# Flattening to 1D
flattened_arr = arr.flatten()

# Transposing (swapping rows and columns)
transposed_arr = arr.T


In [34]:
arr

array([1, 2, 3, 4, 5, 6])

In [35]:
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [37]:
transposed_arr

array([1, 2, 3, 4, 5, 6])

In [38]:
# Concatenating and spliting

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Concatenate along an axis
concat_arr = np.concatenate([arr1, arr2])

# Stacking arrays vertically
vstack_arr = np.vstack([arr1, arr2])

# Horizontal stacking
hstack_arr = np.hstack([arr1, arr2])

# Splitting arrays
split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)  # Splits into 3 equal arrays


In [39]:
arr1

array([1, 2])

In [40]:
arr2

array([3, 4])

In [41]:
concat_arr

array([1, 2, 3, 4])

In [42]:
vstack_arr

array([[1, 2],
       [3, 4]])

In [43]:
hstack_arr

array([1, 2, 3, 4])

In [44]:
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [45]:
# Array manipulation
# Indexing and slicing in multi-dimensional arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Select specific element
print(arr[0, 2])  # Element at row 0, column 2

# Slice rows and columns
print(arr[0, :])  # First row
print(arr[:, 1])  # Second column



3
[1 2 3]
[2 5]


In [46]:
# Masking (logical indexing)
arr = np.array([1, 2, 3, 4, 5])

# Masking: select elements greater than 2
mask = arr > 2
print(arr[mask])  # Elements where the condition is True



[3 4 5]


In [47]:
 # Fancy indexing
arr = np.array([10, 20, 30, 40, 50])

# Select specific elements using indices
indices = [0, 2, 4]
print(arr[indices])  # Elements at indices 0, 2, 4


[10 30 50]


In [49]:
# mathematical Funation
arr = np.array([1, 2, 3])

# Add 5 to each element
add_arr = np.add(arr, 5)

# Multiply each element by 2
mul_arr = np.multiply(arr, 2)


In [50]:
arr

array([1, 2, 3])

In [51]:
add_arr

array([6, 7, 8])

In [52]:
mul_arr

array([2, 4, 6])

In [53]:
# Statistical function

arr = np.array([1, 2, 3, 4, 5])

# Mean
mean_val = np.mean(arr)

# Standard deviation
std_val = np.std(arr)

# Minimum and Maximum
min_val = np.min(arr)
max_val = np.max(arr)


In [54]:
arr

array([1, 2, 3, 4, 5])

In [56]:
mean_val

np.float64(3.0)

In [57]:
std_val

np.float64(1.4142135623730951)

In [58]:
min_val

np.int64(1)

In [59]:
max_val

np.int64(5)

In [60]:
# Linear algebra function

# Dot product of two vectors
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
dot_product = np.dot(arr1, arr2)

# Matrix inversion
matrix = np.array([[1, 2], [3, 4]])
inv_matrix = np.linalg.inv(matrix)


In [61]:
arr1

array([1, 2])

In [63]:
arr2

array([3, 4])

In [64]:
matrix

array([[1, 2],
       [3, 4]])

In [65]:
inv_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
dot_product

np.int64(11)

In [72]:
# Random number generation
# Random float between 0 and 1
rand_float = np.random.rand()

# Random integer between 0 and 10
rand_int = np.random.randint(0, 10)

# Set seed for reproducibility
np.random.seed(42)


In [68]:
rand_float

0.678118574966513

In [69]:
rand_int

9

In [73]:

# Random sample from a list
sample = np.random.choice([1, 2, 3, 4, 5], size=3)

# Shuffle an array in place
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)

# Generate random permutations
perm = np.random.permutation([1, 2, 3, 4, 5])


In [74]:
sample

array([4, 5, 3])

In [75]:
arr

array([4, 2, 3, 1, 5])

In [76]:
np.random.shuffle(arr)

In [77]:
perm

array([2, 1, 4, 5, 3])

In [78]:
# Broadcasting 
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])

# Broadcasting occurs when adding arr1 (1D) to arr2 (2D)
result = arr1 + arr2  # arr1 is broadcast to match the shape of arr2


In [79]:
arr2

array([[1],
       [2],
       [3]])

In [80]:
arr1

array([1, 2, 3])

In [81]:
result

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])